### ISSUE TITLE
Unable to pull an image that requires authentication

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/elemental-cli#389] opened 2022-11-30 05:32 UTC
Build ISO

```
 elemental build-iso  --config-dir /root/derivative --overlay-iso /root/derivative/overlay/iso --debug -o /root/derivative  172.16.1.208/library/example:v10.1
```
```
ERRO[2022-11-30T13:28:28+08:00] Failed installing OS packages: GET http://172.16.1.208/v2/library/example/manifests/v10.1: UNAUTHORIZED: unauthorized to access repository: library/example, action: pull: unauthorized to access repository: library/example, action: pull 
ERRO[2022-11-30T13:28:28+08:00] 1 error occurred:
        * GET http://172.16.1.208/v2/library/example/manifests/v10.1: UNAUTHORIZED: unauthorized to access repository: library/example, action: pull: unauthorized to access repository: library/example, action: pull
```
Unable to pull an image that requires authentication. The public repository is normal

**Comment by Itxaka** [comment] 2022-11-30 09:25
confirmed:

```
INFO[2022-11-30T10:24:31+01:00] Preparing squashfs root...                   
INFO[2022-11-30T10:24:31+01:00] Copying localhost:5000/busybox:latest source... 
INFO[2022-11-30T10:24:31+01:00] Unpacking a container image: localhost:5000/busybox:latest 
INFO[2022-11-30T10:24:31+01:00] Pulling an image from remote repository      
ERRO[2022-11-30T10:24:31+01:00] Failed installing OS packages: GET http://localhost:5000/v2/busybox/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:busybox Type:repository]] 
```

with latest HEAD `version.BuildInfo{Version:"v0.1.3", GitCommit:"5ae32204b0f2160365c8d64997068b2be1a25133", GoVersion:"go1.18.3"}`

**Comment by frelon** [comment] 2023-04-26 13:26
Since rancher/elemental-cli#478 was merged this is now possible, but will require the use of `docker login` or similar, depending on platform. See https://github.com/google/go-containerregistry/blob/main/pkg/authn/README.md for more info.

**Closed as completed by frelon** 2023-04-26 13:26 UTC
Labels: kind/bug, area/cli, area/iso
