### ISSUE TITLE
Some race conditions in our tests

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#124] opened 2022-03-03 10:46 UTC
Looks like our rsync lib sometimes produces race conditions during tests: https://github.com/rancher-sandbox/elemental/runs/5405027256?check_suite_focus=true

**Comment by davidcassany** [comment] 2022-03-03 14:12
~mmm, it could be related to the errors on #122~

Edit: it is not related to #122

**Comment by davidcassany** [comment] 2022-03-04 17:21
Probably this is caused by https://github.com/zloylos/grsync/blob/3aefd55e3b8344bfb7c1fca5e02bfaa49055205c/task.go#L47-L64

To me it looks the rsync task execution does not wait for the stdout and stderr scanner to end before returning. So potentially the Task.Run could eventually end and the `t *Task` object could still be modified by the scanner go routines. It is hard to imagine a use case where it could harm, but I guess this is not `--race` analyzer business, it just reports that the task object could be silently modified after `task.Run()` returned, which could have unpredictable effects.

**Comment by davidcassany** [comment] 2022-03-07 10:29
In my env I can easily reproduce this issue by using the little script:

```bash
for i in {1..20}; do
  echo "Running test $i"
  ginkgo run --label-filter 'install' --fail-fast --slow-spec-threshold 30s --race --covermode=atomic --coverprofile=coverage.txt -p -r ./pkg/action/ || break
done
```

It usually fails 1 out of 10, so with 20 I could not manage to succeed a single time.

I did a hack on `grsync` package to ensure `Task.Run()` waits for the go routines parsing stdout and the errors are simply gone. I executed the above with the patch several times I did not get a single failure.

I am preparing a PR to upstream with the patch.

**Comment by mudler** [comment] 2022-03-07 11:36
> In my env I can easily reproduce this issue by using the little script:
> 
> ```shell
> for i in {1..20}; do
>   echo "Running test $i"
>   ginkgo run --label-filter 'install' --fail-fast --slow-spec-threshold 30s --race --covermode=atomic --coverprofile=coverage.txt -p -r ./pkg/action/ || break
> done
> ```
> 
> It usually fails 1 out of 10, so with 20 I could not manage to succeed a single time.
> 
> I did a hack on `grsync` package to ensure `Task.Run()` waits for the go routines parsing stdout and the errors are simply gone. I executed the above with the patch several times I did not get a single failure.
> 
> I am preparing a PR to upstream with the patch.

:+1: sounds good here, good catch! just a tip, ginkgo has `--until-it-fails` to run tests until a failure is observed, and `--repeat=N` to repeat it N times

**Comment by davidcassany** [comment] 2022-06-03 11:39
This got fixed by using our own fork of grsync.

**Closed as completed by davidcassany** 2022-06-03 11:39 UTC
Labels: kind/bug
